In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)



[1 2 3 4 5]


In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)
print(a.mean())
print(b.shape)


[1 2 3 4 5]
[[1 2]
 [3 4]]
3.0
(2, 2)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())


[1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5


In [4]:
import numpy as np

# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# Basic operations
print(a + 10)
print(a * 2)
print(a.mean())
print(a.sum())

# Shape and size
print(b.shape)
print(b.size)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[11 12 13 14 15]
[ 2  4  6  8 10]
3.0
15
(2, 3)
6


In [5]:
import numpy as np
np.zeros(10)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import numpy as np
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
import numpy as np
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #dimension
print(arr.size) 
print(arr.shape)
print(arr.dtype)

2
6
(2, 3)
int64


In [11]:
import numpy as np
arr=np.array([1.2 , 3.5 ,4.7])
arr_int=arr.astype(int)
print(arr_int)

[1 3 4]


In [12]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0]) #indexing
print(arr[-1])

1
4


In [13]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1:3]) #slicing
print(arr[::3])
print(arr[:3])

[2 3]
[1 4]
[1 2 3]


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])# indexing
print(arr[1])
print(arr[1:,2])#slicing

2
[4 5 6]
[6 9]


In [15]:
import numpy as np
arr=np.array([1,2,3,4])
b=arr.copy()
b[0]=99
print(arr)
print(b)

[1 2 3 4]
[99  2  3  4]


In [16]:
import numpy as np
arr=np.array([1,2,3,4])
arr1=np.array([4,5,6,7])
print(arr+arr1)
print(arr-arr1)
print(arr/arr1)
print(arr*arr1)

[ 5  7  9 11]
[-3 -3 -3 -3]
[0.25       0.4        0.5        0.57142857]
[ 4 10 18 28]


In [17]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]


In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
10
2.5
1
4
1.118033988749895


In [19]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[arr>2])
print(arr>2)

[3 4]
[False False  True  True]


In [ ]:
import numpy as np

# Create an array of 1000 
arr = np.full(1000, "hello")
print(arr)

# Print each on a new line
for emoji in arr:
    print(emoji)

['hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'h

In [21]:
import numpy as np

a = np.array([[1, 2,] ,[ 4, 5]])
b = np.array([[1, 2], [3, 4]])
print(np.dot(a,b))

[[ 7 10]
 [19 28]]


In [22]:
import numpy as np

a = np.array([[1, 2,] ,[ 4, 5]])
b = np.array([[1, 2], [3, 4]])
print(a.T)

[[1 4]
 [2 5]]


In [23]:
import numpy as np

a = np.array([[1, 2,] ,[ 4, 5]])
b = np.array([[1, 2], [3, 4]])
np.random.rand(5) # random no between 0 and 1

array([0.71418233, 0.41236502, 0.23020566, 0.93346833, 0.55341545])

In [24]:
import numpy as np

a = np.array([[1, 2,] ,[ 4, 5]])
b = np.array([[1, 2], [3, 4]])
np.random.rand(3,3) # random no in 3x3 matrix

array([[0.22292258, 0.06058324, 0.00809104],
       [0.11405663, 0.77300541, 0.63507431],
       [0.1614344 , 0.77590061, 0.89867462]])

In [25]:
import numpy as np
a = np.array([[1, 2,] ,[ 4, 5]])
b = np.array([[1, 2], [3, 4]])
np.random.randint(1,120,10)

array([111,  92,  93, 119,   1,  67,  50,  72,  24,  44], dtype=int32)

In [26]:
arr=np.array([1,-2,3,-4,5])
result1=np.where(arr<0,0,arr)
print (result1)
result= 2-np.where(arr%2!=0,-1,arr)
print(result)


[1 0 3 0 5]
[3 4 3 6 3]


In [27]:
data=np.array([14,5,6,7,8,9])
mean_val=np.mean(data)
result=np.where(data>mean_val,mean_val,data)
print(result)

[8.16666667 5.         6.         7.         8.         8.16666667]


In [28]:
import numpy as np
cost=np.array([1500,2000,3000])
print(cost)

[1500 2000 3000]


In [29]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 4, 9],
                [16, 25, 36]])

# Compute square root of each element
sqrt_arr = np.sqrt(arr)

print("Original Array:\n", arr)
print("Square Root Array:\n", sqrt_arr)

Original Array:
 [[ 1  4  9]
 [16 25 36]]
Square Root Array:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
import numpy as np

# -------------------------------
# 1. CREATION
# -------------------------------
print("\n--- CREATION ---")
arr_list = np.array([[1, 2, 3], [4, 5, 6]])
print("From list:\n", arr_list)

zeros = np.zeros((3, 3))
print("Zeros:\n", zeros)

ones = np.ones((2, 4))
print("Ones:\n", ones)

identity = np.eye(4)
print("Identity:\n", identity)

rand_ints = np.random.randint(1, 10, (3, 3))
print("Random integers:\n", rand_ints)

# -------------------------------
# 2. INDEXING & SLICING
# -------------------------------
print("\n--- INDEXING & SLICING ---")
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Single element (0,2):", arr[0, 2])
print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Submatrix (0:2,1:3):\n", arr[0:2, 1:3])

# -------------------------------
# 3. MATHEMATICAL OPERATIONS
# -------------------------------
print("\n--- MATHEMATICAL OPERATIONS ---")
arr_math = np.array([[1, 4], [9, 16]])
print("Square root:\n", np.sqrt(arr_math))
print("Power (squared):\n", np.power(arr_math, 2))
print("Add scalar:\n", arr_math + 10)
print("Multiply scalar:\n", arr_math * 2)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:\n", A @ B)

# -------------------------------
# 4. AGGREGATION
# -------------------------------
print("\n--- AGGREGATION ---")
arr_aggr = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Total sum:", arr_aggr.sum())
print("Column-wise sum:", arr_aggr.sum(axis=0))
print("Row-wise sum:", arr_aggr.sum(axis=1))
print("Column-wise max:", arr_aggr.max(axis=0))
print("Row-wise min:", arr_aggr.min(axis=1))

# -------------------------------
# 5. RESHAPING & FLATTENING
# -------------------------------
print("\n--- RESHAPING & FLATTENING ---")
arr_shape = np.array([[1, 2, 3],
                      [4, 5, 6]])

print("Flattened:", arr_shape.flatten())
print("Reshaped (3x2):\n", arr_shape.reshape(3, 2))
print("Stack vertically:\n", np.vstack([arr_shape, arr_shape]))
print("Stack horizontally:\n", np.hstack([arr_shape, arr_shape]))

# -------------------------------
# 6. ADVANCED LINEAR ALGEBRA
# -------------------------------
print("\n--- ADVANCED LINEAR ALGEBRA ---")
arr_adv = np.array([[1, 2],
                    [3, 4]])

print("Transpose:\n", arr_adv.T)
print("Determinant:", np.linalg.det(arr_adv))
print("Inverse:\n", np.linalg.inv(arr_adv))
eigvals, eigvecs = np.linalg.eig(arr_adv)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


--- CREATION ---
From list:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random integers:
 [[5 5 4]
 [2 6 8]
 [6 1 8]]

--- INDEXING & SLICING ---
Single element (0,2): 30
Second row: [40 50 60]
Third column: [30 60 90]
Submatrix (0:2,1:3):
 [[20 30]
 [50 60]]

--- MATHEMATICAL OPERATIONS ---
Square root:
 [[1. 2.]
 [3. 4.]]
Power (squared):
 [[  1  16]
 [ 81 256]]
Add scalar:
 [[11 14]
 [19 26]]
Multiply scalar:
 [[ 2  8]
 [18 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]

--- AGGREGATION ---
Total sum: 45
Column-wise sum: [12 15 18]
Row-wise sum: [ 6 15 24]
Column-wise max: [7 8 9]
Row-wise min: [1 4 7]

--- RESHAPING & FLATTENING ---
Flattened: [1 2 3 4 5 6]
Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Stack vertically:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Stack horizontally:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]

--- ADVANCED LINEAR ALGEBRA ---
Transpose:
 [[1 3

In [31]:
import numpy as np

# From list
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("From list:\n", arr1)

# Zeros
arr2 = np.zeros((3, 3))
print("Zeros:\n", arr2)

# Ones
arr3 = np.ones((2, 4))
print("Ones:\n", arr3)

# Identity
arr4 = np.eye(3)
print("Identity:\n", arr4)

# Random integers
arr5 = np.random.randint(1, 10, (3, 3))
print("Random integers:\n", arr5)

From list:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random integers:
 [[9 6 5]
 [8 3 6]
 [2 1 7]]


In [32]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Single element (0,2):", arr[0, 2])
print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Submatrix (0:2,1:3):\n", arr[0:2, 1:3])

Single element (0,2): 30
Second row: [40 50 60]
Third column: [30 60 90]
Submatrix (0:2,1:3):
 [[20 30]
 [50 60]]


In [33]:
arr = np.array([[1, 4], [9, 16]])

print("Square root:\n", np.sqrt(arr))
print("Power (squared):\n", np.power(arr, 2))
print("Add scalar:\n", arr + 10)
print("Multiply scalar:\n", arr * 2)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:\n", A @ B)

Square root:
 [[1. 2.]
 [3. 4.]]
Power (squared):
 [[  1  16]
 [ 81 256]]
Add scalar:
 [[11 14]
 [19 26]]
Multiply scalar:
 [[ 2  8]
 [18 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Total sum:", arr.sum())
print("Column-wise sum:", arr.sum(axis=0))
print("Row-wise sum:", arr.sum(axis=1))
print("Column-wise max:", arr.max(axis=0))
print("Row-wise min:", arr.min(axis=1))

Total sum: 45
Column-wise sum: [12 15 18]
Row-wise sum: [ 6 15 24]
Column-wise max: [7 8 9]
Row-wise min: [1 4 7]


In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Flattened:", arr.flatten())
print("Reshaped (3x2):\n", arr.reshape(3, 2))
print("Stack vertically:\n", np.vstack([arr, arr]))
print("Stack horizontally:\n", np.hstack([arr, arr]))

Flattened: [1 2 3 4 5 6]
Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Stack vertically:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Stack horizontally:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [36]:
arr = np.array([[1, 2],
                [3, 4]])

print("Transpose:\n", arr.T)
print("Determinant:", np.linalg.det(arr))
print("Inverse:\n", np.linalg.inv(arr))
eigvals, eigvecs = np.linalg.eig(arr)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [37]:
import numpy as np
import pandas as pd  # optional, for pretty table display

# Marks of 5 students in 3 subjects
marks = np.array([[85, 78, 92],   # Student 1
                  [76, 85, 80],   # Student 2
                  [90, 88, 95],   # Student 3
                  [70, 65, 75],   # Student 4
                  [88, 90, 84]])  # Student 5

df = pd.DataFrame(marks, 
                  columns=["Math", "Science", "English"], 
                  index=["Student 1", "Student 2", "Student 3", "Student 4", "Student 5"])
print(df)

           Math  Science  English
Student 1    85       78       92
Student 2    76       85       80
Student 3    90       88       95
Student 4    70       65       75
Student 5    88       90       84
