In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)



[1 2 3 4 5]


In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)
print(a.mean())
print(b.shape)


[1 2 3 4 5]
[[1 2]
 [3 4]]
3.0
(2, 2)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())


[1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5


In [4]:
import numpy as np

# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# Basic operations
print(a + 10)
print(a * 2)
print(a.mean())
print(a.sum())

# Shape and size
print(b.shape)
print(b.size)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[11 12 13 14 15]
[ 2  4  6  8 10]
3.0
15
(2, 3)
6


In [ ]:
import numpy as np
np.zeros(10)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
import numpy as np
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #dimension
print(arr.size) 
print(arr.shape)
print(arr.dtype)

2
6
(2, 3)
int64


In [15]:
import numpy as np
arr=np.array([1.2 , 3.5 ,4.7])
arr_int=arr.astype(int)
print(arr_int)

[1 3 4]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0]) #indexing
print(arr[-1])

1
4


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1:3]) #slicing
print(arr[::3])
print(arr[:3])

[2 3]
[1 4]
[1 2 3]


In [24]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])# indexing
print(arr[1])
print(arr[1:,2])#slicing

2
[4 5 6]
[6 9]


In [21]:
import numpy as np
arr=np.array([1,2,3,4])
b=arr.copy()
b[0]=99
print(arr)
print(b)

[1 2 3 4]
[99  2  3  4]


In [26]:
import numpy as np
arr=np.array([1,2,3,4])
arr1=np.array([4,5,6,7])
print(arr+arr1)
print(arr-arr1)
print(arr/arr1)
print(arr*arr1)

[ 5  7  9 11]
[-3 -3 -3 -3]
[0.25       0.4        0.5        0.57142857]
[ 4 10 18 28]


In [27]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]


In [28]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
10
2.5
1
4
1.118033988749895


In [30]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[arr>2])
print(arr>2)

[3 4]
[False False  True  True]


In [36]:
import numpy as np

# Create an array of 1000 "🖕"
arr = np.full(1000, "hello")
print(arr)

# Print each on a new line
for emoji in arr:
    print(emoji)

['hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'h